name = "ep-4-ch-1"

[dev-dependencies]
test-drive.git = "https://github.com/fortran-lang/test-drive"
test-drive.tag = "v0.5.0"
veggies.git = "https://gitlab.com/everythingfunctional/veggies"
veggies.tag = "main"

[build]
auto-executables = false
auto-examples = false
auto-tests = false

[[test]]
name = "testdrive_test_matrix_transforms"
source-dir = "test/test-drive"
main = "main.f90"

[[test]]
name = "veggies_test_matrix_transforms"
source-dir = "test/veggies"
main = "main.f90"
