---
repos:
  - repo: https://github.com/PlasmaFAIR/fortitude-pre-commit
    rev : v0.7.2
    hooks:
    - id: fortitude
  - repo: https://github.com/crate-ci/typos
    rev: v1.34.0
    hooks:
      - id: typos
        args:
          - --force-exclude
          - --hidden
