FROM ghcr.io/ucl-arc/fortran-unit-testing-exercises:main

COPY --chown=vscode episodes/4-debugging-a-broken-test /home/vscode/4-debugging-a-broken-test

WORKDIR /home/vscode/4-debugging-a-broken-test/challenge

# Fix intentional bug in code
RUN sed -i -E 's/.*matrix\(row, col\) = temp_matrix\(row, col\)/matrix\(col, row\) = temp_matrix\(row, col\)/g' src/matrix_transforms.f90

# build tests with cmake
RUN cmake -B build -DCMAKE_PREFIX_PATH=/home/vscode/pfunit/build/installed && \
    cmake --build build

# test pfunit with ctest
RUN ctest --test-dir build --output-on-failure
