FROM ghcr.io/ucl-arc/fortran-unit-testing-exercises-parent:main

# Episode 3
COPY episodes/2-intro-to-fortran-unit-tests /2-intro-to-fortran-unit-tests

WORKDIR /2-intro-to-fortran-unit-tests/solution

# test with fpm
RUN fpm test
