FROM ghcr.io/ucl-arc/fortran-unit-testing-exercises:main

COPY --chown=vscode episodes/5-testing-parallel-code /home/vscode/5-testing-parallel-code

WORKDIR /home/vscode/5-testing-parallel-code/challenge

# Fix intentional bug in code
RUN mv ../solution/test_find_steady_state.pf ./test/ && \
    sed -i -E 's/.*LINK_LIBRARIES sut.*/LINK_LIBRARIES sut MAX_PES 8/g' test/CMakeLists.txt

# build tests with cmake
RUN cmake -B build-cmake -DCMAKE_PREFIX_PATH=/pfunit/build/installed && \
    cmake --build build-cmake

# test with ctest, allowing MPI to oversubscribe
RUN PRTE_MCA_rmaps_default_mapping_policy=":oversubscribe" ctest --test-dir build-cmake --output-on-failure
