FROM ghcr.io/ucl-arc/fortran-unit-testing-exercises:main

COPY --chown=vscode episodes/2-intro-to-fortran-unit-tests /home/vscode/2-intro-to-fortran-unit-tests

# Build challenge with cmake
WORKDIR /home/vscode/2-intro-to-fortran-unit-tests/challenge
RUN cmake -B build && \
    cmake --build build

# Build solution with cmake
WORKDIR /home/vscode/2-intro-to-fortran-unit-tests/solution
RUN cmake -B build && \
    cmake --build build
