name = "fortran-unit-test-syntax"

[dev-dependencies]
test-drive.git = "https://github.com/fortran-lang/test-drive"
test-drive.tag = "v0.5.0"
veggies.git = "https://gitlab.com/everythingfunctional/veggies"
veggies.tag = "main"

[build]
auto-executables = false
auto-tests = false
auto-examples = false

[[executable]]
name = "game-of-life"
source-dir = "src"
main = "game_of_life.f90"

[[test]]
name = "veggies_game_of_life_test"
source-dir = "test/veggies"
main = "main.f90"

[[test]]
name = "test-drive_game_of_life_test"
source-dir = "test/test-drive"
main = "main.f90"
